/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alexander' at '05.03.17 03:06' with Gradle 2.14.1
 *
 * @author Alexander, @date 05.03.17 03:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true; //test123
    }
}
