/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alexander' at '05.03.17 02:59' with Gradle 2.14.1
 *
 * @author Alexander, @date 05.03.17 02:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
